config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "comics#index"
  resources :comics, only: [:index, :show]
  # resources :users, only: :show
  resources :sites, only: [:index, :show]
  resources :users, only: :show do
    resources :favorites, only: [:create, :destroy]
  end
  # get "favorites/:user_id/:comic_id" => "favorites#create"
  # delete "/:user_id/:comic_id" => "favorites#destroy"
end

app/models/comic.rb
class Comic < ActiveRecord::Base
  belongs_to :site
  has_many :favorites
  has_many :comments
  has_many :favorite_users, through: :favorites, source: :user
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :comic
  belongs_to :user
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to  :user
  belongs_to  :comic
end

app/models/scrabing.rb
class Scrabing
  # 一気に更新チェック
  def self.check_comics
      # series_check = Comic.all
      #連載チェックフラグを一括オフ
      # series_check.each do |comic|
      #   comic.update = (:series = false)
      # end
      Comic.update_all(:series => false)
      jump_plus
      urasunday
      #連載終了を一括削除
      Comic.delete_all("series = false")
  end

  def self.jump_plus
    agent = Mechanize.new
    site = Site.find(1)
    top_page = agent.get(site.url)
    comic_info = top_page.search(site.info_tag)
    read_link = "http://plus.shonenjump.com/client_info/SHUEISHA/html/player/viewer.html?tw=2&lin=1&cid="
    comic_info.each do |info|
      comic = {}
      comic[:site_id] = 1
      comic[:title] = info.at("p.panel_title").inner_text
      comic[:author] = info.at("p.panel_author").inner_text
      comic[:thumbnail] = Site.find(1).url + info.at("img.panel_image")[:src]
      comic[:list_url] = info.at("a.panel_image_wrap")[:href]
      # html形式とビューアー形式でurlが異なる
      if info.at("span.content_id") == nil
        comic[:new_url] = info.at("span.url_link").inner_text
      else
        comic[:new_url] = read_link + info.at("span.content_id").inner_text
      end
      #文字列で更新日時を取得してからdate型へ変換
      update_str = info.at("p.panel_date").inner_text
      comic[:updated] = Time.strptime(update_str, "%Y年%m月%d日")
      comic[:weekday] = comic[:updated].wday
      comic[:series] = true
      if Comic.find_by(title: comic[:title]) == nil
        Comic.create(comic)
      else
        comic_record = Comic.find_by(title: comic[:title])
        comic_record.update(comic)
      end
    end
  end

  def self.urasunday
    agent = Mechanize.new
    site = Site.find(2)
    top_page = agent.get(site.url)
    comic_info = top_page.search(site.info_tag)
    comic_info.each do |info|
      comic = {}
      comic[:site_id] = 2
      # binding.pry
      unless info.at("a.indexMainImgLink") ==nil
        link = info.at("a.indexMainImgLink")[:href]
        # linkの頭の.が邪魔なのでカット
        index_url = Site.find(2).url + link.slice(1,link.length)
        comic[:list_url] = index_url
        #作品ページを取得して再scrabing
        index_page = Mechanize.new.get(index_url)
        comic[:title] = index_page.at("h1").inner_text
        comic[:author] = index_page.at("h2").inner_text
        comic[:thumbnail] = index_page.at("body section div a img")[:src]
        new_link = index_page.at(".comicButtonBox a")[:href]
        #index_urlの/index.html/以前にnew_linkの先頭の.以降を結合
        index_url =~ /\/index.html/
        comic[:new_url] = $` + new_link.slice(1,new_link.length)
        # # index_url末尾のindex.html/を取り除き、new_link始めの.を除いて結合
        update_str = index_page.at(".comicButtonBox").inner_text
        #正規表現で日付を検索
        update_str =~ /20..\/..\/../
        comic[:updated] = Time.parse($&)
        comic[:weekday] = comic[:updated].wday
        comic[:series] = true
        if Comic.find_by(title: comic[:title]) == nil
          Comic.create(comic)
        else
          comic_record = Comic.find_by(title: comic[:title])
          comic_record.update(comic)
        end
      end
    end
  end

  ## 新サイト追加用テンプレート
  # def self.
  #   site_num =
  #   agent = Mechanize.new
  #   site = Site.find(site_num)
  #   top_page = agent.get(site.url)
  #   comic_info = top_page.search(site.info_tag)
  #   comic_info.each do |info|
  #     comic = {}
  #     comic[:site_id] = site_num
  #     comic[:list_url] =
  #     comic[:title] =
  #     comic[:author] =
  #     comic[:thumbnail] =
  #     update_str =
  #     comic[:updated] = Time.parse(update_str)
  #     comic[:weekday] = comic[:updated].wday
  #     comic[:series] = true
  #     if Comic.find_by(title: comic[:title]) == nil
  #       Comic.create(comic)
  #     else
  #       comic_record = Comic.find_by(title: comic[:title])
  #       comic_record.update(comic)
  #     end
  #   end
  # end


end

app/models/site.rb
class Site < ActiveRecord::Base
  has_many :comics
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many  :favorites
  has_many  :comments
  has_many  :favorite_comics, through: :favorites, source: :comic
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?
  before_action :set_sites

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :nickname
  end

  private
  def set_sites
    @sites = Site.all
  end
end

app/controllers/comics_controller.rb
class ComicsController < ApplicationController
  def index
    @comics = Comic.order(updated: :desc,created_at: :asc)
    @weekdays = ["sun", "mon", "tue", "wed", "thu", "fri", "sat"]
  end

  def show
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    if Favorite.where(comic_id: params[:comic_id], user_id: current_user.id).empty?
      Favorite.create(comic_id: params[:comic_id], user_id: current_user.id)
    end
    @comic = Comic.find(params[:comic_id])
  end

  def destroy
    dislike = Favorite.where(user_id: current_user.id, comic_id: params[:id])
    Favorite.destroy(dislike)
    @comic = Comic.find(params[:id])
  end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @fav_comics = User.find(id: current_user.id).favorite_comics.order(updated: :desc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comics/_comic.html.haml
.comic-tile
  .comic-tile__wrapper
    .comic-tile__thumbnail
      = link_to image_tag(comic.thumbnail, class: "thumbnail"), "comics/#{comic.id}", class: "thumbnail_link"
    .comic-tile__right.comic-info
      .comic-info__title
        %p
          =render "comics/favStar", comic: comic
          = comic.title
      .comic-info__author
        %p= comic.author
      %ul.comic-info__links
        %li= link_to "最新話", comic.new_url
        %li= link_to "作品詳細", comic.list_url
        %li= link_to comic.site.title, comic.site.url

app/views/comics/_favButton.html.haml
.comic-tile__fav-button{id: "comic_#{comic.id}"}
  - if user_signed_in?
    - if current_user.favorite_comics.find_by_id(comic.id)
      = button_to "お気に入り解除", user_favorite_path(user_id: current_user, id: comic), method: :delete, remote: true, class: "like yes like-button"
    - else
      = button_to "お気に入り", user_favorites_path(user_id: current_user,comic_id: comic), remote: true ,class: "like-button not-like yes"

app/views/comics/_favStar.html.haml
%span{id: "comic_#{comic.id}"}
  - if user_signed_in?
    - if current_user.favorite_comics.find_by_id(comic.id)
      = link_to "", user_favorite_path(user_id: current_user, id: comic), method: :delete, remote: true, class: "like fav-icon icon-star-full"
    - else
      = link_to "", user_favorites_path(user_id: current_user,comic_id: comic), method: :post, remote: true ,class: "fav-icon icon-star-full"

app/views/comics/index.html.haml
.left_contents
  .tab
    %ul.tab__selector
      %li#sun 日曜
      %li#mon 月曜
      %li#tue 火曜
      %li#wed 水曜
      %li#thu 木曜
      %li#fri 金曜
      %li#sat 土曜
    .tab__contents
      - @weekdays.each_with_index do |day, i|
        %div{class: "#{day} wday-content"}
          %div.wday-content__tiles
            - @comics.where(weekday: i).each do |comic|
              = render comic

app/views/favorites/create.js.erb
$("#comic_" + "<%= @comic.id %>").html("<%= j(render "comics/favStar", comic: @comic) %>")

app/views/favorites/destroy.js.erb
$("#comic_" + "<%= @comic.id %>").html("<%= j(render "comics/favStar", comic: @comic) %>")

app/views/layouts/_header.html.haml
.nav
  %a.nav__title{:href => "/"} Weebcomic
  - if user_signed_in?
    %ul.nav__menu
      %li.ls-btn
        = link_to "ログアウト", destroy_user_session_path, method: :delete
      %li.ls-btn
        %a{:href => "/users/#{current_user.id}"} マイページ
  - else
    %ul.nav__menu
      %li.ls-btn= link_to "新規登録", new_user_registration_path
      %li.ls-btn= link_to "ログイン", new_user_session_path

app/views/layouts/_sidebar.html.haml
%ul.sidelist
  %p 掲載サイト一覧
  - @sites.each do |site|
    %li
      = link_to site.title, site.url

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=Edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "Weebcomic"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
  %body
    / ヘッダー
    %header.header
      = render partial: "layouts/header"
    .main-wrapper
      / viewごとのコンテンツ
      .container
        = yield
      / サイドバー
      .sidebar
        = render partial: "layouts/sidebar"
    / フッター
    %footer.footer

app/views/users/show.html.haml
.left_contents
  .tab-menu
    %ul.tab-selector
      %li.selected.user_tab
        %h2
        %p
          = current_user.nickname
          さんのマイページ
  .fav_comics.clearfix.comic_tiles
    - @fav_comics.each do |comic|
      .comic_info.clearfix
        = render partial: "comics/comic", locals: {comic: comic }